FROM golang:1.18-alpine
LABEL maintainer="neosouler@gmail.com"

# Set server timezone on server & env
RUN ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
    echo "Asia/Seoul" > /etc/timezone
ENV TZ "Asia/Seoul"

# On alpine, instead of apt-get use 'apk'
RUN apk update
RUN apk --update add openrc --no-cache
RUN apk --update add git --no-cache
RUN apk --update add supervisor --no-cache

# git clone
WORKDIR /go/src
RUN git clone https://github.com/neosouler7/bookstore-go

# build app
WORKDIR /go/src/bookstore-go
RUN go get .
RUN go build -o .

# run supervisor
# RUN mkdir /etc/supervisor.d
# specify the exact location of the config file
# CMD ["supervisord", "-c", "/etc/supervisor.conf"]
